### ISSUE TITLE
Fatal Error (2)

### ISSUE THREAD

**Issue by vphelipe** [deepwn/deepMiner#10]
undefined:2
{"id":1512015481664,"jsonrpc":"2.0","error":{"code":-1,"message":"Unauthenticated"}}
^

SyntaxError: Unexpected token { in JSON at position 315
    at JSON.parse (<anonymous>)
    at pool2ws (/srv/deepMiner/server.js:130:15)
    at Socket.conn.pl.on (/srv/deepMiner/server.js:202:3)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by evil7** [comment]
that's JSONRPC response is OK. I can't found out why you see this err.
`"message":"Unauthenticated"` maybe your setting is NOT right. Wallet Addr? server settings? which Pool? Check in `config.json` first.
It should happened if set by `install.sh`. I'll check code later.

**Comment by vphelipe** [comment]
Hello, thank you for your quick reply. I think I can make your code work with multiple connections by making some changes, in the pool2ws function it is necessary to change the script so that it does not die when it encounters an error, my code now:


// Trans PoolSocket to WebSocket
function pool2ws(data) {
try
{
                var buf;
                data = JSON.parse(data);
                if (data.id === conn.pid && data.result) {
                        if (data.result.id) {
                                conn.workerId = data.result.id;
                                buf = {
                                        "type": "authed",
                                        "params": {
                                                "token": "",
                                                "hashes": conn.accepted
                                        }
                                }
                                buf = JSON.stringify(buf);
                                conn.ws.send(buf,function(error) {
    // Do something in here here to clean things up (or don't do anything at all)
});
                                buf = {
                                        "type": 'job',
                                        "params": data.result.job
                                }
                                buf = JSON.stringify(buf);
                                conn.ws.send(buf,function(error) {
    // Do something in here here to clean things up (or don't do anything at all)
});
                        } else if (data.result.status === 'OK') {
                                conn.accepted++;
                                buf = {
                                        "type": "hash_accepted",
                                        "params": {
                                                "hashes": conn.accepted
                                        }
                                }
                                buf = JSON.stringify(buf);
                                conn.ws.send(buf,function(error) {
    // Do something in here here to clean things up (or don't do anything at all)
});
                        }
                }
                if (data.id === conn.pid && data.error) {
                        if (data.error.code === -1) {
                                buf = {
                                        "type": "banned",
                                        "params": {
                                                "banned": conn.pid
                                        }
                                }
                        } else {
                                buf = {
                                        "type": "error",
                                        "params": {
                                                "error": data.error.message
                                        }
                                }
                        }
                        buf = JSON.stringify(buf);
                        conn.ws.send(buf,function(error) {
    // Do something in here here to clean things up (or don't do anything at all)
});
                }
                if (data.method === 'job') {
                        buf = {
                                "type": 'job',
                                "params": data.params
                        }
                        buf = JSON.stringify(buf);
                        conn.ws.send(buf,function(error) {
    // Do something in here here to clean things up (or don't do anything at all)
});
                }
}catch(error)
{
    console.log("JSON parsing failed: " + error);
}
`

**Comment by evil7** [comment]
At first version that's a rule `coding < 200 lines` because a gamble `Let's make a XMR JSminer proxy or server in just 200` with my teams. hahahha... :P
So I dropped all functions in the socket Error just make it can get working.
🎲 ✍️ 🎃 🙈 

I will add it to handle Error. And logging some debug-info if socket lose again. Thanks.
PR welcome if any others awesome ideas. thanks again.

**Comment by vphelipe** [comment]
Glad to help. Your code is much better than that of the cazala, with that little adjustment works fine. I would like to ask to change the code to work in multiple cores. At the moment it is consuming 40% of only one core of my server. Thanks!!!

**Comment by vphelipe** [comment]
I think I've been able to solve this problem too! The solution I found here:
https://codeforgeek.com/2014/12/cluster-node-js-performance/

I'm going to test it all day tomorrow and post again if you have any news! Thanks again for this incredible script, I was using the x25 code but it has a problem with multicores that I could not solve, and your code solved my problem !!! Thank you!!!!

**Comment by evil7** [comment]
I checked your link in reply. But I'm not very clear in this Problem.
So I think it's a problem but maybe it's not... If your problem is

 `How to set threads with my miner (The user who in mining for me and on my minerPage)`

Let's check demo. there is a API to set threads and CPU idle. So I set that like this one:
```javascript
var addr = 'deepMiner_test';
		var miner = new deepMiner.Anonymous(addr, {
			autoThreads: true
		});
		miner.start();
		// Listen on events
		var found = 0,
			accepted = 0;
		miner.on('found', function () {
			found++;
		});
		miner.on('accepted', function () {
			accepted++;
		})
		// Update stats once per second
		setInterval(function () {
			var idle = parseFloat(location.hash.split('#')[1]) || 0.5;
			var hashesPerSecond = miner.getHashesPerSecond();
			var totalHashes = miner.getTotalHashes();
			var acceptedHashes = miner.getAcceptedHashes();
			miner.setThrottle(idle);
			document.body.innerHTML = '<h2>deepMiner User : ' + addr +
				'</h2><table border="1"><tr><th>Threads</th><th>Hashs</th><th>Found</th><th>Verfiy</th></tr><tr><td>' + parseInt(
					hashesPerSecond) + '</td><td>' + totalHashes + '</td><td>' + found + '</td><td>' + accepted +
				'</td></tr></<table>';
		}, 500);
```
You can see that I just used `#` in href and `miner.setThrottle` to set value for speed and idle.
`var idle = parseFloat(location.hash.split('#')[1]) || 0.5;`

Examlpe:
`https://deepc.cc/demo.html#0.8` (that 20% in used and 80% CPU will keep in free)

that's a API can set threads NOT the `autoThreads` but set by Users.
you can check API document in <https://coinhive.com/documentation/miner#miner-set-num-threads>

* PS: Found a little bug in `Safari`. It can't auto get Cores in Safari. So if you can know who will open your page and you know number of cores. U can set by yourself like `miner.setNumThreads(number)` in your script.

That's how to set Threads for users in browser in JavaScript. Each one of `new Worker` with be a single background jobs and you can hand off with set. Cores choice by user's browser or them's OS system at default. If your problem is in server setting. local node jobs? Server's threads for your this proxy? Maybe U should try your way to fix that U founded.

I don't know is this answer helpful or not. You can try the API at first. Bcs I think the miner will be a user who browser to your page. Good luck. Nice chat in this issue.
Useful move for the little project. Thx a lot.

**Comment by vphelipe** [comment]
Sorry, but I do not think I explained it correctly. The nodejs is running on only one processor core. In the link I sent you have the solution to run in all colors and use the load balance of the nodejs itself to keep everything running clean. It's working like I've never done with x25 and cazala. I am very happy! No other coinhive stratum manages to work with multiple connected miners, my hashrate is tall as it never was. The solution is very simple, create a new file named "cluster.js" in the same folder where "server.js" is, with the content:

var cluster = require('cluster');
var numCPUs = require('os').cpus().length;

if (cluster.isMaster) {

  for (var i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', function(worker, code, signal) {
    console.log('worker ' + worker.process.pid + ' died');
  });
} else {

    //change this line to Your Node.js app entry point.
    require("./server.js");
}

Now just enjoy this great stratum, with its multiples miners !! haha

**Comment by evil7** [comment]
OK. I know what's your means now. Sorry my English not well.
That's a nice idea to set more pid or fork to make balance of the nodejs job in server. I just made it in single bcs in dev now. But it's get rude with CPU. And to hard to adapt if user over 1000. I'll adjustment to more nice at next.

It's time almost 00:00 at night now in `China`. Time to go sleep.
hope u have happy testing time in "tomorrow". I will testing it and try others for this rough problem too in my tomorrow. :P
Happy debug have a good day.
祝你好运 🛌
