### ISSUE TITLE
PoolSocket Error: This socket is closed

### ISSUE THREAD

**Issue by j-lorenzo** [deepwn/deepMiner#11]
Goodnight,

Once the previous incident has been resolved, I added the js code to the page and now, it computes correctly. My CPU is set to 100%, so I guess it must be working.

It seems that it is not sending the data to the pool correctly, I have seen in the README that you say something about the DNS, but the IP is resolved correctly.

I researched a bit, and I went to /root/.forever, where you can see the node logs, where it tells me the following:

> {"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}
> 
> [!] deepMiner_test offline.
> 
> PoolSocket Error: connect ECONNREFUSED 77.76.228.4:3333
> 
> PoolSocket Closed.
> 
> PoolSocket Error: This socket is closed
> 
> [>] Request: deepMiner_test
> 
> {"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}
> 
> [!] deepMiner_test offline.
> 
> PoolSocket Error: connect ECONNREFUSED 77.76.228.4:3333
> 
> PoolSocket Closed.
> 
> PoolSocket Error: This socket is closed
> 
> [>] Request: deepMiner_test
> 
> {"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}
> 
> [!] deepMiner_test offline.
> 
> PoolSocket Error: connect ECONNREFUSED 77.76.228.4:3333
> 
> PoolSocket Closed.
> 
> [!] null offline.

**Comment by evil7** [comment]
is that wallet addr setting done? See Ur log says `PoolSocket` always close when miner start login. which `Pool` you are using now? maybe U can try another. Example: `pool.usxmrpool.com:3333`
