### ISSUE TITLE
How do I know whether the system works or not?

### ISSUE THREAD

**Issue by crackwei** [deepwn/deepMiner#13]
Hello,this's a great project,thank you first.
but i have a problem,how do I know whether the system works or not?because all the param (threads,hashs,found,verify) ouput are 0.and there aren't any log to visit,i'm not sure whether the worker is mining.

**Comment by evil7** [comment]
Run `forever list` to checking is server running or not.
And if the status of server job show red `STOP`. See error info in log file (.forever/log/xxxxx.log ???). Maybe pool url or domain or wallet addr or SSL cert blablabla  what ever something in config is missing. (Location show with forever list cmd)

Add all settings server it need in `config.json` and run `forever restartall` try to run this.

PS: I don't know why is that `install.sh` can't make this all setting done. Maybe some wrong codes I writed. I'll check the install script next day.

**Comment by crackwei** [comment]
when i run :forever list,it shown:"info:    No forever processes running",but when i run "netstat -an", i see that the port already on listen.and some connected already build from "127.0.0.1"(ESTABLISHED).
why?

**Comment by evil7** [comment]
Server use nginx at 80 and script sever at 7777 (default). The links from 127.0.0.1 connection between script and nginx.
Try fix do
1. Checking config.json
1. debug once running with `node /srv/deepMiner/server.js` see if success or error info come out.
1. over the debug. Try `forever start /srv/deepMiner/server.js` to starting demon for server.

**Comment by crackwei** [comment]
this is the error:
[!] Error: Something wrong with websocket buffer. `type: authed`
[!] Error: Something wrong with websocket buffer. `type: job` (with authed)

**Comment by evil7** [comment]
can U post your config.json details?
I can't make a true answer for this. I need checking more info.
Now we just can known it's some bad happened when create server's websocket. But many reasons can make this error happen...

**Comment by crackwei** [comment]
{ "lhost": "127.0.0.1",
    "lport": 58888,
    "domain": "miner.edog.online",
    "pool": "xmr-us-east1.nanopool.org:14444",
    "addr": "42qR2igJAvFDCXVUYL66uHYrXfAH6uNMw1HiJXEi44J1gJ2CMcLGTXjDh1xr3FDLpphssDxHC4ajmGAFHqh5SztZTbcc6Zj.cr/test@qqtest",
    "pass": "x"
}

**Comment by evil7** [comment]
looks like no wrong with your settings. So I'll check more at tomorrow. bcs It's 01:13 AM In China...
I must go sleep now or I'll be late to go working tomorrow. I will check it and reply when I wake up and get to offices.

**Comment by crackwei** [comment]
ok, you are very kind,thank you.

**Comment by crackwei** [comment]
hello,friend,did you fixed this problem,it shown me the error even your original program.

**Comment by evil7** [comment]
Yep. default pool in config change now fixd at yesterday. Try it. If any others bug let me know.
U can see new line in readme or check the first in opening issue in list.

**Comment by crackwei** [comment]
sorry, it still the same error.my nodejs run in AWS EC2,version is 8.9.2.

{"id":1512748428131,"jsonrpc":"2.0","error":null,"result":{"id":"537360247597098","job":{"blob":"0606aeeaaad1059ce5bbaa7a614cae5438835905e1d0da0493044202f101590c77d0640dcc449c00000000bf4a92b3bdce626bc7db3c5f9c4337e9512112e8d6ff85e8219df62dfcfad3bf08","job_id":"936261733854189","target":"6e128300"},"status":"OK"}}


[!] Error: Something wrong with websocket buffer. `type: authed`
[!] Error: Something wrong with websocket buffer. `type: job` (with authed)
[<] Response: deepMiner_test

{"jsonrpc":"2.0","method":"job","params":{"blob":"06069febaad1055406c7801034e0c49b114d0b49ec45a2848d65ccc40b9d5eebe97f7d597f24fe00000000d6398e493f7d144db592227f36f5e9062f24995c4dc1de3c6e146163a61e033d09","job_id":"792439188249409","target":"6e128300"}}


[!] Error: Something wrong with websocket buffer. `type: job`

**Comment by evil7** [comment]
did u have change your pool setting? and is that iptables make this ports banned?

**Comment by evil7** [comment]
After all done. remember restart server will `forever restartall`. I have NO AWS EC2 servers. So can't help u with this. But other users running all good now.

**Comment by crackwei** [comment]
I confirm that it can be worked now,the pool already have the workers records. but i don't know why it always show this error.maybe need the brower support webassembly?i'm not javascript programer,so this error is diffcult to me.

**Comment by evil7** [comment]
support webassembly or asm. Edge chrome ff all working find. Maybe that's the problem u have. U can try in other v8 browser.
