### ISSUE TITLE
Uncompiled C or C++ code?

### ISSUE THREAD

**Issue by ben-ic** [deepwn/deepMiner#14]
Can you publish the C or C++ code you use to create the WASM file to the repo by any chance?

**Comment by evil7** [comment]
Not created by me. I using `file.wasm` a same from `CoinHive.com`.
I have try build by self with `ccminer` and `xmr-stak` but some mistakes show up yet.
So I choice them's wasm file... just a file working to finish `NightCrypto` functions.
if U want to build new `file.wasm` or learn how it work. Check the crypto libs from <https://github.com/fireice-uk/xmr-stak/tree/master/xmrstak/backend/cpu/crypto> and white book in <https://github.com/deepwn/deepMiner/blob/master/CryptoNight.txt>

I think I learn the `wasm` and `asm.js` things not much well than U guys. I working in hospital so I don't know how to code this and show U the real right way to build this. Sad and sorry can't help u on this : (

**Comment by ben-ic** [comment]
Thanks.  Will need to figure out how to create my own wasm file then.  
My assumption is that coinhive wasm files weren't released under the MIT license or any other open source license which means we can't use them in our own projects.

**Comment by evil7** [comment]
`Coinhive` script files no open source. BUT that `cryptoNight` are free to use. And for anybody.
So is that `Coinhive` working under `cryptoNight` license frist? Or U build it but it's used all belong to a free one? : ) Oops..

This `deepMiner` is a obj to learn how it js and the miner work. Not for commercial products. So I have NOT thinking about this problem...

And by the way. A word from Harley Quinn : "Come on! V R bad guys (hackers?) :P"

U can used this version in dev and do some learn with it. When U fix this little problem. Build it in new for your own objects.

PS: "Come on U R the IT guy!" Use it! and good luck.
