### ISSUE TITLE
CPU percentage

### ISSUE THREAD

**Issue by adobromilskiy** [deepwn/deepMiner#2]
I didn't see functionality for changing CPU percentage.

How I can change it? Or implement it please.

**Comment by evil7** [comment]
Same as coinhiveJS API. Ideas come from that so none changes like that and used like that. For the API and func U can check this API Reference <https://coinhive.com/documentation/miner>

At all this U just need setting what u should set. This obj's will set config.json if run install.sh OR setting it up by yourself. That all.

U can use any API. But only miner.Anonymous() works now. bcs NO backend support for .User() in this version (U can use it same one). I'll add it dashboard or some like status views maybe next. Maybe after webUI finish. 

Easy to save the 30% feed~ and not hard to install. And don't forget add SSL if wrong with https request the js and websocket in wss. So good luck dude.

If all done and it's already helpful. U can just close issue. China timezone UTC+8 so... I think I'm in sleeping when u c over this line

OMG. It's a lots of words in this 1 reply hahahah bcs I wanna help more and tell more details. So, good night ;)

晚安，伙计。为了明天正常工作，我必须睡了

**Comment by adobromilskiy** [comment]
Thank you! It was helpful.
