### ISSUE TITLE
Is it possible to run this on github pages site?

### ISSUE THREAD

**Issue by seiterseiter** [deepwn/deepMiner#21]
As the title says :)

**Comment by evil7** [comment]
JS file and the page can put to Pages. But the proxy server must running in your own server. Or need a nodejs server by yourself. And `heroku` is OK too. javascript in web can NOT trans TCP but in nodejs it can be. That the hard problem you need to know. So answer is NOP.

**Comment by evil7** [comment]
Over 24 hours. Closed now.
