### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by lorexx** [deepwn/deepMiner#22]
Hello all ,
more then 3  days to understand how to set up correctly with my mining pool but nothing!!!

94.140.116.213/web/demo.html 

The page appear but mining not start, i have try many time with other setup but nothing :,(

Pool adress : 94.140.116.213/pool

Help me please to understand...

Regards !

**Comment by evil7** [comment]
Is  that U used sub path to run web? You need  change the path to load in JavaScript file. Or change your path to use the root

**Comment by evil7** [comment]
don't used just from IP. Add a domain for it. and don't used different sub-path. Or mark your changed in codes you need. Because it just using under `nginx` now in all my codes. So that wrong happened with add on a `web` path maybe.
Over 24 hours. Closed now.
