### ISSUE TITLE
demo有计算，CPU到100%，但矿池显示没速度。

### ISSUE THREAD

**Issue by linkboy2007** [deepwn/deepMiner#23]
demo.html有计算，CPU到100%，但矿池显示没速度。
我把https改成了 http，wss 改成了ws

矿池是 http://www.bi-chi.com/ 的。是否是 https没改好？

**Comment by linkboy2007** [comment]
换成  https://monero.crypto-pool.fr/ 情况一样。
http://js.wlongchina.com/test.html
http://js.wlongchina.com/demo.html

**Comment by linkboy2007** [comment]
又或者其实有速度，要多挂一会儿？我挂了几分钟。。

**Comment by evil7** [comment]
我这点你的demo页有速度啊，正在挖。矿池在线查询没速度么？正常的应该有的。在当前使用的矿池手动搜索你的地址，会显示当前速率才对

**Comment by linkboy2007** [comment]
是啊，我也手动查了。没速度。配置目前如下。

"pool": "xmr.crypto-pool.fr:3333",
    "addr": "44dSztdLUfJKBJWd5NFmqaaKg6x3ihw1HKP4kUv3HK3AQXN5SF4QH9sTudpX17Q42riDnJVMnzxHwUdSAu9sj4tCTbxVdTp",
    "pass": "",
    "key": "",
    "cert": ""



https://monero.crypto-pool.fr/  查询 没有速度。所以就很奇怪了。不知道在挖啥东西。。。

**Comment by evil7** [comment]
你矿池换了应该没问题，确定钱包地址换了么？自己申请个收款地址就是了，config里所有的配置就跟普通矿工设置基本一样。

**Comment by linkboy2007** [comment]
我贴了配置config 。

**Comment by evil7** [comment]
修改配置后`forever restartall`不然srv载入内存的配置还是之前的

**Comment by linkboy2007** [comment]
我直接 init 6，重启服务器的。目前 再  forever restartall  一下。但感觉不会有变化。。。

**Comment by evil7** [comment]
你看看脚本的log，或者先关掉forever，手动`node /srv/deepMiner/server.js`看看标准输出有没有流量，按道理是没错的，暂时我也不知道你这个问题(ﾟﾍﾟ?)???

**Comment by linkboy2007** [comment]
root@iZb:/srv/deepMiner# forever restartall
info:    Forever restarted processes:
data:        uid  command       script                   forever pid id logfile                 uptime       
data:    [0] Wmrx /usr/bin/node /srv/deepMiner/server.js 883     898    /root/.forever/Wmrx.log 0:1:9:20.810 
root@iZb:/srv/deepMiner# 



查询 https://monero.crypto-pool.fr/  44dSztdLUfJKBJWd5NFmqaaKg6x3ihw1HKP4kUv3HK3AQXN5SF4QH9sTudpX17Q42riDnJVMnzxHwUdSAu9sj4tCTbxVdTp

Your Stats & Payment History
not found

**Comment by linkboy2007** [comment]
我不知道是不是 我把所有https 改成 http会有影响？ 但感觉 既然跑起来 应该有效果。。奇怪了。。
主要是https搞证书太麻烦。。

**Comment by evil7** [comment]
你直接服务器看看你能ping通这个矿池么，然后手动开启脚本，看看debug信息，有没有流量或者报错吧

**Comment by linkboy2007** [comment]
ping 没有问题。

返回包也有


  deepMiner (idea from coinhive.js)
  Worker for own Pool or personal XMR Wallet
  By evil7@deePwn
  
----------------------------------------------------------------------------------------

 Listen on : 127.0.0.1:7777
 Pool Host : xmr.crypto-pool.fr:3333
 Ur Wallet : 44dSztdLUfJKBJWd5NFmqaaKg6x3ihw1HKP4kUv3HK3AQXN5SF4QH9sTudpX17Q42riDnJVMnzxHwUdSAu9sj4tCTbxVdTp

----------------------------------------------------------------------------------------

[>] Request: deepMiner_test

{"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}

[<] Response: 55e6b4bebf62b8e80e03a47e

{"id":"55e6b4bebf62b8e80e03a47e","jsonrpc":"2.0","error":null,"result":{"id":"777420066040940","job":{"blob":"0606d5bfd4d105d0a429b5b5df23ea2251e0ebd146eff4bc898113267a3e02389737506081028e0000000019b0678d9418a4bffd89e3a7976b80aafbc5f2e2354b61727eea4496c186eaa917","job_id":"160122135002166","target":"11a40300"},"status":"OK"}}

**Comment by linkboy2007** [comment]
Listen on : 127.0.0.1:7777
 Pool Host : xmr.crypto-pool.fr:3333
 Ur Wallet : 44dSztdLUfJKBJWd5NFmqaaKg6x3ihw1HKP4kUv3HK3AQXN5SF4QH9sTudpX17Q42riDnJVMnzxHwUdSAu9sj4tCTbxVdTp

----------------------------------------------------------------------------------------

[>] Request: deepMiner_test

{"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}

[<] Response: 4108294f3adc0d6861fc1b89

{"id":"4108294f3adc0d6861fc1b89","jsonrpc":"2.0","error":null,"result":{"id":"262727263313718","job":{"blob":"0606d5bfd4d105d0a429b5b5df23ea2251e0ebd146eff4bc898113267a3e02389737506081028e000000000b51b50f72f02b4bf502757e7109b7bc6af50e30dcfa0ecaf5745d5e70b2784717","job_id":"377369529823772","target":"11a40300"},"status":"OK"}}


[<] Response: 4108294f3adc0d6861fc1b89

{"jsonrpc":"2.0","method":"job","params":{"blob":"0606c3c1d4d105520b74e6512d1682d588d0896b3716229627122ddc5899c4036fd8c44320ae690000000071056df41885319c88a02a6d0162da4f0cc61015840b775011c6fa212873199e18","job_id":"537209765613079","target":"11a40300"}}

**Comment by linkboy2007** [comment]
{"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}

这个有没有问题？

**Comment by evil7** [comment]
也有可能是你的这个难度太大，一般是hash确认才会统计的，你换个难度小点的矿池试试吧，这个都1w8难度了

**Comment by linkboy2007** [comment]
{"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}

这个有没有问题？

有没有推荐的矿池测试？  本来不行就自己搭建再测试，但还是蛮折腾的。。呵呵

**Comment by linkboy2007** [comment]
另外 如果我要调整线程和cpu 怎么设置参数？ 我参考 conhive 改成如下。好像不对。

<script>
    var miner = new deepMiner.Anonymous('test',{
        threads: 1,
        autoThreads: false,
        throttle: 0.9,
        forceASMJS: false
});
        miner.start();
</script>

**Comment by evil7** [comment]
线程可以用`setThreads`啊兄弟
`setThrottle`是设置预留cpu量的，你上面设置1线程，又空闲90%，基本没算力了。
google翻译一下就好了，跟coinhive的api是一样的。

**Comment by evil7** [comment]
Over 24 hours. Closed now.
