### ISSUE TITLE
deepMiner_test

### ISSUE THREAD

**Issue by JBelinchon** [deepwn/deepMiner#24]
Hi, I have just installed deepMiner and tested demo.html

This is what I see in the logs:

`[>] Request: deepMiner_test

{"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}

PoolSocket Error: connect ECONNREFUSED 198.71.51.169:8080

PoolSocket Closed.`

What is that about "deepMiner_test"??

Many thanks in advance.

**Comment by evil7** [comment]
"deepMiner_test" is nothing just a testing name for next versions function about ID the miner. Your problem at pool link. check if u can do `ping` the pool. check your DNS or something.

**Comment by JBelinchon** [comment]
Hi
I can ping the pool...

```
ping pool.elitexmr.com
PING pool.elitexmr.com (198.71.51.169) 56(84) bytes of data.
64 bytes from 198.71.51.169: icmp_seq=1 ttl=49 time=162 ms

```

By I get a refused connection:

```
telnet 198.71.51.169 8080
Trying 198.71.51.169...
telnet: Unable to connect to remote host: Connection refused

```
I am trying with a diferent pool from https://github.com/timekelp/xmr-pool-choice

I choosed: 
mine.xmrpool.net:3333

Testing with demo.html again I get the following on the log:

```
[>] Request: deepMiner_test

{"type":"auth","params":{"site_key":"deepMiner_test","type":"anonymous","user":null,"goal":0}}

[<] Response: 6f7db7b355e0f36a86e6b884

{"id":"6f7db7b355e0f36a86e6b884","jsonrpc":"2.0","error":{"code":-1,"message":"No login/password specified"}}

```

I am tring to figure out that is going on but I don´t get it.

**Comment by JBelinchon** [comment]
Looks like it was a issue with the pool.
If I use this pools: minexmr.pooldd.com everything is working nice.

👍

**Comment by evil7** [comment]
yep. I test that's some trouble from the pool.

**Comment by vphelipe** [comment]
Hello, the problem with the pool has already been resolved.

**Comment by evil7** [comment]
Over 24 hours. Closed now.
