### ISSUE TITLE
Could you help me with the following questions.

### ISSUE THREAD

**Issue by christianvargasforero** [deepwn/deepMiner#25]
Good morning,

Could you help me with the following questions:

How many hashs has each block found and each block verified?

How could you calculate the amount of hashs generated indibidualmete for each machine that is running deepMiner?

Sometimes I see that the amount of hashes that are increasing is rebooted, and as time goes by the reboot is prolonged for a longer time, this because it happens?

**Comment by evil7** [comment]
You should learning about how monero worked and to know how the pool and miner worked first.

1. <https://getmonero.org/resources/moneropedia/blockchain.html>
1. some info in <https://www.monero.how>
1.  Read some objects of pool in github. Like <https://github.com/clintar/cryptonote-xmr-pool>

this object just a proxy to transfer TCP and websocket

**Comment by christianvargasforero** [comment]
> @evil7 
perfect, thank you very much,
I want is to make an approximate account of how many hashes generated each machine that is running the deepMiner according to the amount of hashes found and verified.

**Comment by evil7** [comment]
Yep that's it. U need counting it by Uself when in different machine. And a list u can see in one of those links. Hashing power comes from CPU not the JavaScript. Maybe 50h/s/CPU for browser mined. that's number from my macbook pro with half CPU used. (i7 2.9GHz and 50% idle setting)
