### ISSUE TITLE
GPU acceleration?

### ISSUE THREAD

**Issue by clousr** [deepwn/deepMiner#3]
Not exactly an issue but have you thought about re writing your worker to enable the GPU via https://github.com/turbo/js or similar?

Note: had no Idea on how to email you

**Comment by evil7** [comment]
1) GPU engine need change jsAPI to use WebGL (same for turbo.js) OR rebuild GPUminer in wasm. But it NOT support in some browser-release. Just useful in safari-dev OR chrome-dev now. That's too much work to do for me. Maybe webGL over dev I'll add it.
2) There are no much diff for speeds between GPU & CPU. Bcs it run to mining XMR. So only GPU + CPU running together speeds will up to double. BUT that make user's PC become a toaster! that's more HOT more NOISE than just 1 way working. (That U can see why I just set half-CPU-using in this demo)
So about the GPU support. Emmm... :P No update for that right now. But U can fork it and building a GPU func add on if U wish it be. welcome to PR~

**Comment by clousr** [comment]
Yeah, when I saw I needed to rebuild almost everything for it, I called it quits. Although, I might just wait or ask someone to build it out for me. Thank you for your all your hard work so far. It is much appreciated.

**Comment by evil7** [comment]
Thank U too. That's a good idea for running in Full-Power. I will try to done it. But maybe long time to take by only me dev it. :P At all, I like this idea~
