### ISSUE TITLE
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer

### ISSUE THREAD

**Issue by apachler** [deepwn/deepMiner#31]
Following error on executing the demo.html:

11:23:43.334 Successfully compiled asm.js code (loaded from cache in 12ms)  6757cd97-3938-4a70-a33e-32d29200f957
11:23:43.354 Successfully compiled asm.js code (loaded from cache in 3ms)  6757cd97-3938-4a70-a33e-32d29200f957
11:23:43.481 RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer  6757cd97-3938-4a70-a33e-32d29200f957:10519

seems the line 10519 in web/lib/cryptonight-asmjs.min.js triggers the problem:
    this.input = new Uint8Array(heap, Module._malloc(84), 84);

Any idea?

**Comment by evil7** [comment]
cleanup the cache and retry? which browser? IE?

**Comment by apachler** [comment]
No, luck ... i use Firefox ... the strange thing is that your demo site on https://deepc.cc/demo.html is working but if i try to run it from my server it dont work.

It seems that something is wrong with getting the files:
![grafik](https://user-images.githubusercontent.com/3908272/34295499-f2c560fe-e70d-11e7-8c3d-69fbf09ee5e6.png)

**Comment by evil7** [comment]
OK I'll check it. thx
