### ISSUE TITLE
asmjs部分运行不起来，会出现input和output长度错误

### ISSUE THREAD

**Issue by zanedeng** [deepwn/deepMiner#32]
this.input = new Uint8Array(heap, Module._malloc(84), 84);

Uncaught RangeError: Invalid typed array length: 84
    at typedArrayConstructByArrayBuffer (<anonymous>)
    at new Uint8Array (native)
    at new CryptonightWASMWrapper

**Comment by zanedeng** [comment]
下了新版本可以了

**Comment by evil7** [comment]
嗯，之前忘记更新mem文件了，申请模拟内存时候貌似会出错
