### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by kevrat** [deepwn/deepMiner#35]
## Check list

- [x] Ask for HELP.

- [ ] Report a BUG.

- [ ] Have an IDEA.

- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but not helpful.

## Issue info

Trying to run it in docker container with alpine, some pain with nginx and certbot. Has anyone done this and can share their dockerfile?

**Comment by evil7** [comment]
No docker building for it yet.
I'll re-write this object all in `ES6` and upload it to npm repo.
When I finish this WebUI and manager parts. You can only `npm install deepMiner` and create a image for it by yourself. :)
At now, maybe you need create a docker image and ssh to do build it.
But NO one test for it. debug needed if in docker. do NOT trust and run any docker without you and no checking.

**Comment by evil7** [comment]
Over 24h. Closed
