### ISSUE TITLE
[HELP] 不同ip连接问题

### ISSUE THREAD

**Issue by 0es** [deepwn/deepMiner#40]
你好，我就直接用中文了XD
不同ip同时连接，只有一个有速度。是哪里的问题，还是本身设置的问题？

**Comment by evil7** [comment]
什么是不同IP同时连接？同一个浏览器下，默认只会有一个标签栏加载的，API里可以设置。

**Comment by 0es** [comment]
另一个不同ip的机器，打开这个网页。已经打开的网页的速度就会变成0

**Comment by 0es** [comment]
没搞明白是不是ip的问题

**Comment by evil7** [comment]
我这边貌似没办法复现这个问题。你是外网IP不同么？你是怎么测试的？

**Comment by evil7** [comment]
我开了6个IP不同的设备都没出现这个问题，你看看是不是丢包太高被矿池ban了。

**Comment by 0es** [comment]
我突然也没法复现了，可能是凑巧网页挂起了
先close了
