### ISSUE TITLE
How restart only miner (no vps)?

### ISSUE THREAD

**Issue by freebet** [deepwn/deepMiner#44]
## Check list

- [x] Ask for HELP.

- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but unsloved.

Hello,

How  restart only miner (no vps) after change config.json, possible?

Thanks.

**Comment by 3bkry** [comment]
restart nodejs would help

**Comment by evil7** [comment]
`forever restartall` or `forever list` and do restart what one need be.

**Comment by qfdk** [comment]
To response your question, there are a lot for solutions:

1. as evil7 mentioned using `forever`
2. install `nodemon` with command `npm i nodemon -g` then use command `nodemon cluster.js` (you can change your file, nodemon will restart the node.js)
3. install `pm2` then use pm2

**Comment by evil7** [comment]
yep some kind of deamon which U wanna used. u can change it if you want

**Comment by freebet** [comment]
okey, thanks for your solutions.

in reality i want  change config.json and pointed new pool/wallet without losing hashrate, possible something like that?

**Comment by evil7** [comment]
you can just restart it. In website they will auto re-connect to deepminer if losed the websocket. So that no big deal. lose maybe just 5s. at all
