### ISSUE TITLE
WebGL implement

### ISSUE THREAD

**Issue by andrehrferreira** [deepwn/deepMiner#49]
Hi, gentlemen, how are you?

I would like your help regarding the changes needed to run the script with WebGL instead of using Webworker because of not appearing on the system monitor as CPU usage, I already started to take a look at some mining scripts bitcoin and I already saw that it is possible. can you help me ?

Thank you

https://github.com/jwhitehorn/jsMiner
https://github.com/derjanb/hamiyoca

**Comment by evil7** [comment]
GPU is not good than CPU for Monero (cryptonight's coin) mining.
And it's too many work to do if wanna make a openGL object to running with webGL.
but it's easy to build a C obj to a WASM.

It's default 50% cpu used and set with `#0.x` in demo page. you can go <https://digxmr.com/demo.html#0.1> see this work. 
(I checked it's the pool down. it have changed to minekitten.io for this demo, check it again.)
and it's will show up CPU state on system monitor. like this on mine:

![tim 20180111093057](https://user-images.githubusercontent.com/6292673/34804263-991274c0-f6b2-11e7-950c-d591ed9d1e13.jpg)


and check this if it's helpful:
GPU & CPU BENCHMARKS FOR MONERO MINING <http://monerobenchmarks.info/>

**Comment by andrehrferreira** [comment]
Hi, thanks for the feedback.

The question is not the performance, but rather that using CPU for processing in the browser makes the process very exposed, any low level user can monitor with the system monitor increased use of resources, with GPU use the process may have a lower performance, but it is more difficult for any user to identify that the site is performing such a process, I loved the idea of making an object in WASM or ASM.js, I will follow this path and I will be giving feedback

Thank you

**Comment by evil7** [comment]
yep. that's a nice idea yours. Another team version developing with webGL now. Not working well than I think so we stop it, and very exposed too. bcs high speed with PC fan with told to anyone "here is some GPU work running now" :P 
Maybe release that one some day ~
Happy coding ~ dude~
