### ISSUE TITLE
Firefox can’t establish a connection to the server at wss://mydomain.com:7777/proxy/.

### ISSUE THREAD

**Issue by sabudbai** [deepwn/deepMiner#5]
I have an issue setting up deepMiner. Here is my config.json
```
{
    "lhost": "0.0.0.0",
    "lport": 7777,
    "domain": "mydomain.com",
    "pool": "mydomain.com:3333",
    "addr": "xxxxxxMYMONEROADDRESxxxxxxxxxx",
    "pass": ""
}

```
The node is started correctly and listens on port 7777. But still with these config in deepMiner.js and worker.js I can't get it working.

I have no SSL Certificate on my server.. Could that be the issue? Any help much appreciated!

**Comment by evil7** [comment]
Yep. Pls use SSL first. U can use `certbot` to do like in DEMO what I do.
Check the README and DOC for `certbot`.
PS: U can use `https` link cross in `http` site but NOT working when upside down.
AND! If U realy want to using without SSL. Change ALL `https / wss`  to `http / ws` in conf-files and func settings.

**Comment by evil7** [comment]
Sorry. I read it again and find what's the real question it is. :P
Maybe U should rewrite the `config.json` and in `worker.js` to set. If `install.sh` not finish setting that. Please redo setting by yourself.
When it set up. Check if already a job in `forever list` U can restart by `forever restartall` OR only u need start if it no running after installed. use `forever start [full realpath for JS]`

That's it. If NOT working again! Maybe U need try clone and reinstall again.
