### ISSUE TITLE
Xmr node proxy

### ISSUE THREAD

**Issue by mport88** [deepwn/deepMiner#51]
## Check list

- [x] Ask for HELP.

- [ ] Report a BUG.

- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but unsloved.

Is it possible to use the deepMiner through the xmr-node-proxy? I just can not find a normal manual.

**Comment by JBelinchon** [comment]
That is exacly my setup. 
 JS Weminer Client —> deepminer  —> xmr-node-proxy  —> POOL
Just configure deepminer in config.json to point to your xmr-node-proxy, And configure your xmr-node-proxy in the config.json to point your prefered public pool.

**Comment by mport88** [comment]
@JBelinchon thx. hmm interesting. So, in the deepminer config.json file does not need to specify the address, pool, password, but simply refer to the xmr node proxy server port. I understand correctly?

**Comment by JBelinchon** [comment]
No, no, You still have to set your wallet address and password (x or whatever) on both deepminer and xmr-node-proxy.
