### ISSUE TITLE
Is there a source code for .wasm file?

### ISSUE THREAD

**Issue by hippich** [deepwn/deepMiner#52]
Is there a source code for .wasm file?

**Comment by evil7** [comment]
sorry I don't have this sources~ Just a copy from coinhive. But you can checking the link which I put in readme for it (The cryptonig.c some functions and libs from a PC-miner project).
And it easy build a new from c project. Or debugging this with EMCC dev-tools.

**Comment by evil7** [comment]
<https://github.com/deepwn/deepMiner/issues/14>

And I found the cryptonight.c sources maybe come from here:  <https://github.com/JayDDee/cpuminer-opt/tree/master/algo/cryptonight>

I just working on learn the wasm file now and not completely dump yet. can't totally known how it trans to wasm file.
we need tracking the function name in worker.js, and review it in the c file, to dig the parts out, debugging with it to kown is here the function really come from.

So wish this two links can help u too, if you wanna do the same jobs. :)

**Comment by hippich** [comment]
Thanks! This should let me get going!

**Comment by Goldeneum** [comment]
yes we should rewrite it in javascript. so we can hide the hashing work from debugger and anti virus !
