### ISSUE TITLE
360极速浏览器 失效？

### ISSUE THREAD

**Issue by linkboy2007** [deepwn/deepMiner#53]
360 极速 9.0 不会挖矿。chrome 正常。不知道是不是有这个情况？

**Comment by linkboy2007** [comment]
https://js.wlongchina.com/demo.html  所有国产浏览器都生效qq、百度等。只有chrome有效？

**Comment by linkboy2007** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help

**Comment by evil7** [comment]
或内的估计开始屏蔽脚本了吧，“我大360完美防御”什么的。。之后再改吧，18年初有点忙

**Comment by linkboy2007** [comment]
好像版本问题，chrome 新的也是 no native wasm support detected

**Comment by evil7** [comment]
看一下你文件夹下是不是wasm文件被杀毒软件删了，我本地貌似没这个问题的。

**Comment by evil7** [comment]
或者是更新版本后，默认缺省不开启webassembly了

**Comment by linkboy2007** [comment]
用的阿里云的server。应该没东西杀wasm文件。我测试 coinhive正常的 。奇怪了。

**Comment by evil7** [comment]
那重新git clone一下吧，然后用install.sh重新设置安装

**Comment by colinrui** [comment]
还是不要用阿里云了  国内的都不要用啦  现在都在严查  而且阿里方面已经放话坚决抵制此类应用

**Comment by linkboy2007** [comment]
这和阿里云也有关系？重新安装也是没效果。
