### ISSUE TITLE
对于每日最低大几千万IP量服务器需要怎样才够

### ISSUE THREAD

**Issue by colinrui** [deepwn/deepMiner#54]
对于之前bolg提到的2c4g的服务器不用cdn能够？
看了你诙谐幽默详细的几篇文章之后很想跟你更多的沟通一下
我有在你fb上面m你  或者你可以给我私个联系方式？( ´▽` )ﾉ

**Comment by evil7** [comment]
如果流量很大，可以将deepminer做多几个成分布，但是年初很忙我还没开始着手构造，所以现在是一个用户浏览就模拟成一台矿机。
如果是后端pool这样占用，肯定会很不友好浪费资源，所以，其实只需要搭建1个pool，或者使用公共pool，然后按量添加deepMiner中间件。
比如后期我会将1k的sessions流量汇总为1个miner集合，也避免了连接断开，导致deepminer<-->pool流量造成DDoS或者过多畸形未完成任务。
这个会在之后pool的协议学习，目前开源pool的安全隐患，一起在写文再分析分析。

**Comment by evil7** [comment]
你可以加我QQ，我开完会去freebuf回你pm
