### ISSUE TITLE
coinhive rights?

### ISSUE THREAD

**Issue by ego008** [deepwn/deepMiner#55]
下图是什么情况？

<img width="749" alt="aa" src="https://user-images.githubusercontent.com/47590/34926793-c602cc22-f9ec-11e7-8773-ebbdee3d22d6.png">

看好 deepMiner，不知道是不是要低调？

**Comment by evil7** [comment]
恩，有可能是被投诉ban了吧。。之前ph牛的github账号也直接被ban了。。因为放出了Java反序列化漏洞的验证性靶机docker。。估计是被某风控大数据误判，然后误伤了吧。。

**Comment by evil7** [comment]
刚问了cazala，那个项目是被github关掉的。他已经给github发了反馈申请但是预计解封无望。
他把项目重新放到gitlab了，没给出新的项目地址。可能不会开放吧，之后关注他博客和推好了。
谢谢提醒，我这边也会注意的，适当修改部分项目功能。感谢！

**Comment by letlet** [comment]
估计他那个是直接用了coinhive的商标的缘故吧
