### ISSUE TITLE
ASK - blog - creating new pool

### ISSUE THREAD

**Issue by jensej** [deepwn/deepMiner#56]
Hello In read.me I see point about creating own pool, but is only in Chinese lang. (link to your blog)
Is where I can find any explanation in eng?

**Comment by evil7** [comment]
Hi @jensej 
here is an ENGLISH "how to" paper I found: <http://betbybitcoin.com/setup-monero-mining-pool-using-node-cryptonote-pool/>

And you should check out pool's document pages and readme first, I think.
<https://github.com/Snipa22/nodejs-pool>
<https://github.com/zone117x/node-cryptonote-pool>
<https://github.com/zone117x/node-stratum-pool>

here is a build ALL in One, maybe u can use it:
<https://github.com/zone117x/node-open-mining-portal>
