### ISSUE TITLE
ASK - setting throttle not working

### ISSUE THREAD

**Issue by jensej** [deepwn/deepMiner#58]
Hello.
I'm trying to set throttle like in doc but it is not working. I do like this:
```
var addr = 'test_test';
var bla = new deepMiner.Anonymous(addr, {throttle: 0.3});
bla.start();
```
But always using CPU is around 90%.

**Comment by evil7** [comment]
Emmm... It's work with my testing.
Maybe you can use the `bla.setThrottle()` after `bla.start()` to do this.
pls test it.
