### ISSUE TITLE
why it only work few seconds?

### ISSUE THREAD

**Issue by windrunner414** [deepwn/deepMiner#59]
我测试的时候发现，这个只会挖一会儿，然后就会自动停，这是什么原因？

**Comment by windrunner414** [comment]
好像在移动设备也挖不了

**Comment by evil7** [comment]
因为一般矿池会ban掉`low-share攻击`可能的链接，而web挖矿因为算力不足一般选择低算力的端口(高diff也会ban只是没这么快但是对web端不友好经常挖不到)，所以反复的刷新或者访问新页面就等于反复链接，就容易被当成DDoS类的无效连接被ban掉。
这个问题正在改跟进修改新的框架，会在新版本里改。

In normal, the pool with banned who was mining on `low-share ports` and with no `success-share`. So if you have one site connecting with 50 peoples, and maybe 10 persons flash the page or go to next page, that will put a new session to pool. (to your deepMiner srv, and your srv linking to pool). So if to many `unwork-session` and `fast-link-in` it will become a `DDoS-Attack` that your from your server IP. So it be banned.
I will fix this in new framework and update at next version.

**Comment by windrunner414** [comment]
但是并没有反复刷新什么的，算力确实很低 大概130H/s 但是好像使用cryptonoter并没有出现这种情况。然后这个手机端也是算力0== cryptonoter也是正常的。这种算力低该怎么办？只能自建pool吗？用xmr-node-proxy听说算力掉得很严重。。。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: ИЭΛЭS 7ΙΛЭ <notifications@github.com>
发送时间: Thursday, January 18, 2018 8:24:32 AM
收件人: deepwn/deepMiner
抄送: windrunner414; Author
主题: Re: [deepwn/deepMiner] why it only work few seconds? (#59)


因为一般矿池会ban掉low-share攻击可能的链接，而web挖矿因为算力不足一般选择低算力的端口(高diff也会ban只是没这么快但是对web端不友好经常挖不到)，所以反复的刷新或者访问新页面就等于反复链接，就容易被当成DDoS类的无效连接被ban掉。
这个问题正在改跟进修改新的框架，会在新版本里改。

In normal, the pool with banned who was mining on low-share ports and with no success-share. So if you have one site connecting with 50 peoples, and maybe 10 persons flash the page or go to next page, that will put a new session to pool. (to your deepMiner srv, and your srv linking to pool). So if to many unwork-session and fast-link-in it will become a DDoS-Attack that your from your server IP. So it be banned.
I will fix this in new framework and update at next version.

―

**Comment by evil7** [comment]
那就用cryptonoter他们的吧，我这项目不会长时间维护，工作比较忙没太多时间优化。抱歉了。。

**Comment by windrunner414** [comment]
好吧

发自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: ИЭΛЭS 7ΙΛЭ <notifications@github.com>
发送时间: 2018年1月20日 16:01
收件人: deepwn/deepMiner
抄送: windrunner414; Author
主题: Re: [deepwn/deepMiner] why it only work few seconds? (#59)


那就用cryptonoter他们的吧，我这项目不会长时间维护，工作比较忙没太多时间优化。抱歉了。。

―

**Comment by gotoco** [comment]
I have similar issue when the miner is mining about few seconds, then stop for a while and rerun again. I see some kind of rectangle wave like on cpu (I tested on windows and OSX systems with Chrome and Firefox browser). What is causing that behaviour, is it possible to remove it?

**Comment by evil7** [comment]
bcs it have an one test-hash running at frist. to testing if you can mining in web. and few secends linking the pool start mining you can check the deepminer.js. It's a fork same like coinhive.min.js
