### ISSUE TITLE
How can I use it with Minergate account?

### ISSUE THREAD

**Issue by j-lorenzo** [deepwn/deepMiner#6]

**Comment by evil7** [comment]
Not a account but a Wallet Address! So U need know what's Ur Address first!
(PS: That a Addr like a random string. Show up in [Account Details] OR [Account Setting] in usual)
This object is a miner like others miner but just build in JS. Any pool if it working on `XMR` it's OK. Need U change Addr in `config.json` to yours. U can follow steps when run `install.sh`. It will help U to set all config.
