### ISSUE TITLE
Optymalization - connections SOCKET and FILES (SCREEN)

### ISSUE THREAD

**Issue by jensej** [deepwn/deepMiner#60]
Hello.
I'm when is a lot of users then I get nginx 500 Internal Server Error, logs display this:

> [alert] 27493#0: 768 worker_connections are not enough

What exacly I need to do, because when I changed value in nginx.conf doesn't work.

**Comment by gotoco** [comment]
Did you specify worker_connections in /etc/nginx/nginx.conf ?

**Comment by jensej** [comment]
Yes. But still this error. I don't have enought users to used this connections

**Comment by gotoco** [comment]
How many users do you have? I just tried this for 2 days with ~ 300 users and works totally fine

**Comment by jensej** [comment]
300-800

**Comment by evil7** [comment]
Sorry I haven't testing it over 100 sessions yet. And some bug with fix next. less patch for now.

**Comment by jensej** [comment]
What I should do now?

**Comment by evil7** [comment]
Please waiting for next update. coming soon. thanks for feedback

**Comment by jensej** [comment]
soon is week or few days?

**Comment by freebet** [comment]
i updated all apt later install again deepMiner and problem done, you can try.

`apt-get update`

**Comment by jensej** [comment]
@freebet sorry I don't understand. I didn't see any changes on code

**Comment by freebet** [comment]
not need change on code.
login ssh and just join this command:

`apt-get update`

**Comment by freebet** [comment]
sory, no done, sametimes have problem.

**Comment by jensej** [comment]
Please I trying to find why server.js crash.
Check my deduction, On screen You can see: 
- current online connected to port 80
- current opened socked and files
<img width="476" alt="zrzut ekranu 2018-01-24 o 23 42 01" src="https://user-images.githubusercontent.com/13967042/35361203-c1c97d7e-0160-11e8-96a8-8feb9d5ccd9b.png">

**Comment by evil7** [comment]
you can try this one: <https://www.npmjs.com/package/coin-hive-stratum>
project sources here: <https://gitlab.com/cazala/coin-hive-stratum>
