### ISSUE TITLE
{"id":"dd114e046422e9ec8100b45d","jsonrpc":"2.0","error":{"code":-1,"message":"invalid address used for login"}}

### ISSUE THREAD

**Issue by wanglong167** [deepwn/deepMiner#62]
{"id":"dd114e046422e9ec8100b45d","jsonrpc":"2.0","error":{"code":-1,"message":"invalid address used for login"}}

这个是什么问题呢 我访问demo.html没有工作

**Comment by wanglong167** [comment]
https://m.hd3p.com/demo.html#0.2

**Comment by evil7** [comment]
看看pool能从srv端ping通么。感觉你是不是没填钱包地址？或者pool有密码要求？或者pool联不通？

**Comment by wanglong167** [comment]
用的这个狂池  config.json里面没见填密码的地方
https://github.com/zone117x/node-cryptonote-pool

**Comment by wanglong167** [comment]
http://pool.hd3p.com

**Comment by evil7** [comment]
按你这个自己搭建的<http://pool.hd3p.com/#getting_started>
应该是填IP:PORT把？ 在pool的设置处用 `123.207.216.143:3333` 或者同一个服务器上就用 `127.0.0.1:3333` 试试吧

**Comment by wanglong167** [comment]
我就是 127.0.0.1:3333

**Comment by wanglong167** [comment]
{
    "lhost": "127.0.0.1",
    "lport": 7070,
    "domain": "m.hd3p.com",
    "pool": "127.0.0.1:3333",
    "addr": "4LYWaNAqVLsD2BoEqi64szTFV64R8xz7QPhxgHFeDrrPU5nii5uWGXh128UUYXayQHFUrjojugSByAyf2VHatc9gL9kKqvgkWe6EjAv3Zp",
    "pass": null,
        "key": "",
        "cert": ""
}

**Comment by wanglong167** [comment]
我换其他人的矿池 demo是工作的

**Comment by evil7** [comment]
那应该是矿池设置问题了，。我试了你的，确实不行。

**Comment by wanglong167** [comment]
谢谢拉  我再想想办法 可能系统原因 我用的是centos 7 
你有矿池吗

**Comment by evil7** [comment]
没有了，我的上次服务器重装了。不想再配置了，好麻烦。。

**Comment by evil7** [comment]
pass 用 “x”试试把

**Comment by wanglong167** [comment]
试了没用    算了 我也懒得搞了   一天也挖不到多少钱
