### ISSUE TITLE
how to reduce hash difficulty from 1024 to 256

### ISSUE THREAD

**Issue by 3bkry** [deepwn/deepMiner#63]
how to reduce hash difficulty from 1024 to 256
the number of hashes to solve a one job.
I think its 1024 because it takes more than coinhive takes so how to reduce it.

## Check list

- [x] Ask for HELP.

- [ ] Report a BUG.

- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but unsloved.

**Comment by evil7** [comment]
1. In some way, you need setting it in pool-config. so u can't change it if using a pool not belong to you.
1. BUT if it can set diff with login, add the diff you want. (the pool running under `cryptonote-universal-pool` maybe)

PS：
<https://github.com/fancoder/cryptonote-universal-pool>
<http://cryptonotemining.org/>

![1](https://user-images.githubusercontent.com/6292673/35672997-24ba62c0-077b-11e8-903c-da35d8350016.png)

**Comment by evil7** [comment]
but it's must have a min-diff in pool-setting so you must know what the pool's config.
<https://github.com/fancoder/cryptonote-universal-pool/blob/master/config.json#L49>

and, there is key if you wanna set diff at login:
<https://github.com/fancoder/cryptonote-universal-pool/blob/master/config.json#L56>

when `fixedDiff.enable: true` you can keep diff fixed. (depend on config of pool)

**Comment by 3bkry** [comment]
Why there no submit operations? 
![image](https://user-images.githubusercontent.com/14781002/35767321-ea8da99e-08f2-11e8-829e-ca92fd681404.png)


in coinhive
![image](https://user-images.githubusercontent.com/14781002/35767336-40f6bbc2-08f3-11e8-9c98-dbcfd435ed72.png)


i think there is a proplem and i can`t solve it.
