### ISSUE TITLE
[!] Error: not opened

### ISSUE THREAD

**Issue by 3bkry** [deepwn/deepMiner#64]
## Check list

- [x] Ask for HELP.

Hello, Can you please tell me how to solve this error.

![image](https://user-images.githubusercontent.com/14781002/35780076-3221d554-09df-11e8-986a-287be35d9993.png)

- [ ] Report a BUG.

- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but unsloved.

**Comment by evil7** [comment]
looks like there are some wrong with server connecting the pool. check can you `ping` the pool or success linking with the pool.
(U can try run a normal mined in server to mining on this same pool if it running OK.)
