### ISSUE TITLE
关于安装后https无法正常访问

### ISSUE THREAD

**Issue by hzs2004** [deepwn/deepMiner#67]
用了您的一件脚本安装后(https://raw.githubusercontent.com/deepwn/deepMiner/master/install.sh)主站可正常访问但是一旦访问http://etn.ptree.top/deepMiner.js就会被重定向到https://etn.ptree.top/且无法访问

请问应如何解决？

祝您新春快乐，情人节也快乐

**Comment by hzs2004** [comment]
并且访问demo没速度，本机cpu无明显增长

**Comment by evil7** [comment]
https下的，访问http设置是会跳转回主站。。
