### ISSUE TITLE
Hello please help with this issue, avast warning

### ISSUE THREAD

**Issue by 3bkry** [deepwn/deepMiner#68]
## Check list

- [x] Ask for HELP.
Hello please help with this issue, avast warning
![image](https://user-images.githubusercontent.com/14781002/36314883-d8244a5a-133e-11e8-81dd-1ea49ac2ca63.png)

I need to know where this code to encrypt it.
i did it for deepMiner.js but i can`t find those files.

- [ ] Report a BUG.
- [x] Already check [README.md](https://github.com/deepwn/deepMiner/blob/master/README.md) but unsloved.

**Comment by evil7** [comment]
go encrypto worker.js
