### ISSUE TITLE
Demo.html only shows "deepMiner"

### ISSUE THREAD

**Issue by j-lorenzo** [deepwn/deepMiner#7]
I saw the code, and maybe it has to display the H/s and more, but it only shows the text "deepMiner"

**Comment by evil7** [comment]
U check demo.html first dude

**Comment by j-lorenzo** [comment]
Sorry but I can't understand your reply, when I access my website it shows this:

![image](https://user-images.githubusercontent.com/16794234/33344613-da2199d2-d489-11e7-98f8-b7c39f31498e.png)

**Comment by j-lorenzo** [comment]
https://minar.bananascraft.es/demo.html

**Comment by j-lorenzo** [comment]
I'm doing some tests in a digitalocean droplet, if you want I can grant you access to see what could be happening ;)

**Comment by evil7** [comment]
I see that test page in your server. Look in `console.err` U forget to replace DOMAIN in your demo page. It can NOT got the JS file. There U set `localhost` for script that wrong. because that why your page can't running.

**Comment by j-lorenzo** [comment]
Now it seems to work, thank you for your support, I'll be wating for the backoffice you are deveolping to monitoring the hashes the people are computing to me.
