### ISSUE TITLE
Feature request: Add support for Hodlcoin - 1GB AES Pattern Search POW

### ISSUE THREAD

**Issue by AmiT177** [deepwn/deepMiner#74]
Website:
http://hodlcoin.com/

HOdlcoin source code:
https://github.com/HOdlcoin/HOdlcoin

Algo:
https://github.com/HOdlcoin/HOdlcoin/blob/HODLCoin0.11.3/src/primitives/block.cpp
https://github.com/HOdlcoin/HOdlcoin/blob/HODLCoin0.11.3/src/patternsearch.cpp

**Comment by evil7** [comment]
I will check when I have time. thx
