### ISSUE TITLE
Demo page inaccessible

### ISSUE THREAD

**Issue by 40thoughts** [deepwn/deepMiner#75]
Hello, just a report to tell you that the demo page doesn't seem to be accessible anymore.
Checked this on Chromium browser and Firefox using multiple different DNS'.
It doesn't seem to come from my setup since it was working on the same one the last time I checked (though it was a few months ago).
Thanks anyway for the work you've done.

**Comment by evil7** [comment]
demo was down bcs it's stop developing now. you can check this <https://github.com/notgiven688/webminerpool> if you need a web miner for monero7.
will some day I re-update this project when I found some funny ideas to add in with it.

**Comment by 40thoughts** [comment]
OK, thanks a lot for the advice.
I guess this issue should be closed, or not, for the others to get the tip unless you put it on the README (since I didn't see anything in it unless I'm blind ;-P)

**Comment by evil7** [comment]
yep. I'll keep this open. thx
