### ISSUE TITLE
你好，手机上没有效果是怎么回事？

### ISSUE THREAD

**Issue by aa224488** [deepwn/deepMiner#77]
在手机上全部浏览器和电脑的百度浏览器上没有效果，是浏览器不支持WebAssembly的原因吗？我是用您的这个网站测试的https://deepool.net/miner.html，要怎么才可以在手机上有效果和电脑的百度浏览器上有效果，谢谢 @evil7

**Comment by evil7** [comment]
首要是要浏览器支持webAssembly。我的demo好像已经被国内运营商blacklist了。。手机使用wifi可以访问，但是独用4G貌似不解析了。
