### ISSUE TITLE
你好，关于webAssembly的问题

### ISSUE THREAD

**Issue by aa224488** [deepwn/deepMiner#78]
如果浏览器不支持webAssembly的情况下要怎么才可以有效果，coinhive这个平台的可以在不支持webAssembly的浏览器上可以挖矿。 @evil7

**Comment by evil7** [comment]
asmjs不打算考虑，本来wasm速度就挺慢的，asmjs还要低能10%左右。coinhive同时是在做hash验证码产品，所以会加入全版本支持。
