### ISSUE TITLE
关于cryptoNight算法的问题

### ISSUE THREAD

**Issue by JacketPants** [deepwn/deepMiner#79]
Hi,

如果我想要使用新的cryptoNight算法，比如将要开始使用的CryptoNight variant 2或者CryptoNight-Lite，我可以自己使用Emscripten编译他们吗？请问有相关的教程吗？

**Comment by evil7** [comment]
可以的，我没写doc介绍如何迁移自己的算法，但是你可以自己用emcc编译新的wasm用新的cryptoNight变种。
目前我使用的是cryptoNight的原始算法和变种，主要对应Monero old和Monero v7算法。
关于emcc编译wasm可以用我cryptonight-wasm内的脚本，安装emcc的方法就自己谷歌一下吧。
至于改算法细节和如何适应框架的任务分配、算法切换，可以看看worker.js载入的c的关键函数，再去看看切换逻辑，就知道怎么判断算法版本又是如何切换的了。
